using System.Text.RegularExpressions;
using ImmichTools.ReplyData;

namespace ImmichTools.Helpers;

public class FilePrioritizer
{
    public const int RawPriority = -99;

    static FilePrioritizer()
    {
        RegexFileTypePriorities = FileTypePriorities.Select(p =>
        {
            var pattern = p.Pattern
                .Replace(".", "\\.")
                .Replace("*", ".*?");
            return (new Regex("\\A" + pattern + "\\z", RegexOptions.IgnoreCase | RegexOptions.Compiled), p.Priority);
        }).ToArray();
    }
    
    // List taken from https://github.com/immich-app/immich/blob/main/server/src/utils/mime-types.ts
    private static readonly (string Pattern, int Priority)[] FileTypePriorities = [
        // Default for everything we don't recognize
        ("*", 0),
        
        // RAW images
        ("*.3fr", RawPriority),
        ("*.ari", RawPriority),
        ("*.arw", RawPriority),
        ("*.cap", RawPriority),
        ("*.cin", RawPriority),
        ("*.cr2", RawPriority),
        ("*.cr3", RawPriority),
        ("*.crw", RawPriority),
        ("*.dcr", RawPriority),
        ("*.dng", RawPriority),
        ("*.erf", RawPriority),
        ("*.fff", RawPriority),
        ("*.iiq", RawPriority),
        ("*.k25", RawPriority),
        ("*.kdc", RawPriority),
        ("*.mrw", RawPriority),
        ("*.nef", RawPriority),
        ("*.nrw", RawPriority),
        ("*.orf", RawPriority),
        ("*.ori", RawPriority),
        ("*.pef", RawPriority),
        ("*.raf", RawPriority),
        ("*.raw", RawPriority),
        ("*.rw2", RawPriority),
        ("*.rwl", RawPriority),
        ("*.sr2", RawPriority),
        ("*.srf", RawPriority),
        ("*.srw", RawPriority),
        ("*.x3f", RawPriority),
        
        // These are generated by Camera Raw when denoising
        ("*Enhanced-NR.dng", -1),

        // Consider .psd edited
        ("*.psd", 1)
    ];

    private static readonly (Regex Regex, int Priority)[] RegexFileTypePriorities;

    public static int GetFilePriority(Asset asset)
    {
        return RegexFileTypePriorities
            .LastOrDefault(p => p.Regex.IsMatch(asset.OriginalFileName))
            .Priority;
    }
}